services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - memcached
      - ollama

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  ollama:
    image: ollama/ollama:rocm  # Replace with the correct image name for Ollama
    ports:
      - "11434:11434"  
    deploy:
      resources:
        reservations:
          devices:
            - driver: amd
              count: all
              capabilities: [gpu]
