services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - memcached
      - ollama

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  ollama:
    image: ollama/ollama:rocm
    ports:
      - "11434:11434"
    devices:
      - "/dev/kfd:/dev/kfd"  # Device for ROCm
      - "/dev/dri:/dev/dri"  # Device for Direct Rendering Infrastructure
    volumes:
      - ollama:/root/.ollama
      
volumes:
  ollama: