services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
      - "11211:11211"
      - "11434:11434"
    env_file:
      - .env
    depends_on:
      - memcached

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

