services:
  llama-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app 
      - ~/certs:/certs  # Mount the directory containing your SSL certificates
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
    depends_on:
      - memcached
      - ollama

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia  # Use the NVIDIA runtime
      
volumes:
  ollama: